### ISSUE TITLE
App.Metrics not reporting to InfluxDB/Graphite locally (docker-compose/grafana/dotnet 6)

### ISSUE THREAD

**Issue by gabriellima09** [AppMetrics/AppMetrics#735]
I built an api using dotnet 6 to report metrics to Grafana + InfluxDB/Graphite and I'm trying to test locally the report for either InfluxDB/Graphite locally by using their docker images, but unfortunally neither works.

The databases can connect on Grafana datasources and also I can see the metrics output info on `/metrics` and `/metrics-text` endpoints, but for some reason I couldn't find out, the data isn't sent to any database.

**Grafana Datasource Config**
![image](https://user-images.githubusercontent.com/32204447/175440215-dbd81f3a-355b-4e70-8f7e-e3dd7f5fb7ed.png)

**Output  `/metrics` and `/metrics-text` **
![image](https://user-images.githubusercontent.com/32204447/175441088-ced14b22-d0f5-4dea-b8a6-0960ff767e68.png)

**Configs:**

**`docker-compose.yml`**
```
version: "3"

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - grafana_network
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - influxdb
      - graphite

  graphite:
    image: graphiteapp/graphite-statsd:latest
    ports:
    - 8080:80
    networks:
      - grafana_network
    volumes:
      - graphite_data

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    networks:
      - grafana_network
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=demo
      - INFLUXDB_USER=grafana
      - INFLUXDB_USER_PASSWORD=password
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin 
      - INFLUXDB_ADMIN_PASSWORD=password 

networks:
  grafana_network:

volumes:
  grafana_data:
  influxdb_data:
  graphite_data:
```

**configs on _Program.cs_ dotnet 6 api:**

```
using App.Metrics;
using App.Metrics.AspNetCore;
using Microsoft.AspNetCore.Mvc;

var builder = WebApplication.CreateBuilder(args);

builder.WebHost.UseKestrel(options => 
{
   options.AllowSynchronousIO = true;
});

// Add services to the container.
builder.Services.AddControllers();

builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

builder.Host
    .ConfigureMetrics(builder =>
        {
            // builder
            // .Report
            // .ToGraphite(options =>
            // {
            //     options.Graphite.BaseUri = new Uri("net.tcp://172.21.0.3:8080");
            //     options.FlushInterval = TimeSpan.FromSeconds(5);
            // });

            builder
            .Report
            .ToInfluxDb(options => 
            {
                options.InfluxDb.BaseUri = new Uri("http://172.21.0.2:8086/");
                options.InfluxDb.Database = "demo";
                options.InfluxDb.UserName = "grafana";
                options.InfluxDb.Password = "password";
            });
        })
    .UseMetrics();

builder.Services    
    .AddMetrics()
    .AddAppMetricsSystemMetricsCollector()
    .AddAppMetricsCollectors();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.MapControllers();

app.UseMetricsAllEndpoints();

app.Run();
``` 

**.csproj:**
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>grafana_metrics</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="App.Metrics.AspNetCore.All" Version="4.2.0" />
    <PackageReference Include="App.Metrics.AspNetCore.Endpoints" Version="4.2.0" />
    <PackageReference Include="App.Metrics.Graphite" Version="4.2.0" />
    <PackageReference Include="App.Metrics.InfluxDB" Version="4.2.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.2.3" />
  </ItemGroup>

</Project>
```

I followed the instructions, I've tried to change the configs, downgrade to .net 3.1 and also checked the samples on this repository but still not working :/. Am I doing anything wrong?

**Comment by gabriellima09** [comment]
Solved by using the following configs:

**Program.cs**
```
using App.Metrics;
using App.Metrics.AspNetCore;
using Microsoft.AspNetCore.Mvc;

var builder = WebApplication.CreateBuilder(args);

builder.WebHost.UseKestrel(options => 
{
   options.AllowSynchronousIO = true;
});

builder.Services
    .AddControllers()
    .AddMetrics();

// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();
    
builder.Services.AddAppMetricsHealthPublishing();
builder.Services.AddAppMetricsSystemMetricsCollector();

builder.Host
        .ConfigureMetricsWithDefaults(builder =>
                {
                    builder.Report.ToInfluxDb(options =>
                    {
                        options.InfluxDb.Database = "demo";
                        options.InfluxDb.BaseUri = new Uri("http://127.0.0.1:8086");
                        options.InfluxDb.UserName = "user";
                        options.InfluxDb.Password = "123";
                        options.InfluxDb.CreateDataBaseIfNotExists = true;
                        options.FlushInterval = TimeSpan.FromSeconds(5);
                    });
                })
            .UseMetrics();

var app = builder.Build();

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.MapControllers();

app.UseMetricsAllEndpoints();
app.UseMetricsAllMiddleware();

app.Run();
```

**.csproj**
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>MyProject</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="App.Metrics.AspNetCore.All" Version="4.2.0" />
    <PackageReference Include="App.Metrics.AspNetCore.Endpoints" Version="4.2.0" />
    <PackageReference Include="App.Metrics.Graphite" Version="4.2.0" />
    <PackageReference Include="App.Metrics.InfluxDB" Version="4.2.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.2.3" />
  </ItemGroup>

</Project>

```

**docker-compose.yml**
```
version: '3'
services:

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: always
    ports:
    - 8086:8086
    environment:
    - INFLUXDB_DB=demo
    - INFLUXDB_USER=user
    - INFLUXDB_ADMIN_ENABLED=true
    - INFLUXDB_ADMIN_USER=admin
    - INFLUXDB_ADMIN_PASSWORD=123
    volumes:
    - influxdb:/var/lib/influxdb

  grafana:
    container_name: "grafana"
    image: "grafana/grafana:latest"
    restart: always
    ports:
    - 3000:3000
    volumes:
    - grafana:/var/lib/grafana

volumes:
  influxdb:
  grafana:
```

**OBS: On Grafana datasource config you use the _container_name_ to set it up and on dotnet app use the localhost IP 127.0.0.1**
